apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_LINK: cG9zdGdyZXNxbDovL3Bvc3RncmVzOkFkaXR5YV8xMjE5OTBAbWluaWt1YmUtcG9zffeqwgfeqg2Z5a3Vrd2N3NDE5LmFwLXNvdXRoLTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi9wb3N0Z3Jlcw==