apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: 3-tier-app-eks
type: Opaque
data:
  DB_USERNAME: cG9zdGdyZXMK
  DB_PASSWORD: RGRaSzZFQmVXWQo=
  SECRET_KEY: ZGV2LXNlY3JldC1rZXk=
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOkRkWks2RUJlV1lAbWF5MjUtZGV2LWRiLmN2aWs4YWNjdzJ0ay5hcC1zb3V0aC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvcG9zdGdyZXMK