services:
  frontend:
    image: livingdevopswithakhilesh/craftista:frontend-9ce2a27f66c068ec12c2b0d14cf79014686d2cad
    build:
      context: ./frontend
    ports:
      - "8040:3000"
    networks:
      - craftista

  catalogue:
    image: livingdevopswithakhilesh/craftista:catalogue-9ce2a27f66c068ec12c2b0d14cf79014686d2cad
    ports:
      - "5050:5000"
    networks:
      - craftista

  catalogue-db:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops
      POSTGRES_DB: catalogue
    networks:
      - craftista

  recco:
    image: livingdevopswithakhilesh/craftista:recommendation-9ce2a27f66c068ec12c2b0d14cf79014686d2cad
    ports:
      - "8030:8080"
    networks:
      - craftista

  voting:
    image: livingdevopswithakhilesh/craftista:voting-9ce2a27f66c068ec12c2b0d14cf79014686d2cad
    build:
      context: ./voting
    ports:
      - "8081:8080"
    depends_on: 
      - catalogue
    networks:
      - craftista

networks:
  craftista:
