apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2-tier-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # Maximum number of pods that can be created above desired replicas
      maxUnavailable: 0  # Maximum number of pods that can be unavailable during update
  selector:
    matchLabels:
      app: attendance-app
  template:
    metadata:
      labels:
        app: attendance-app
    spec:
      containers:
      - name: attendance-app
        image: 879381241087.dkr.ecr.ap-south-1.amazonaws.com/may-flask:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"           # 1 CPU core
            memory: "512Mi"    # 512 Megabytes memory
          requests:
            cpu: "20m"        # 500 milliCPU (0.5 CPU core)
            memory: "128Mi" 
        ports:
        - containerPort: 8000
        env:
        - name: DB_LINK
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_LINK
---
apiVersion: v1
kind: Service
metadata:
  name: attendance-app
spec:
  selector:
    app: attendance-app
  ports:
  - port: 8000
    targetPort: 8000
  type: NodePort