---
# Handlers for the common role

- name: restart sshd
  systemd:
    name: sshd
    state: restarted
    daemon_reload: yes

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
    daemon_reload: yes

- name: restart auditd
  systemd:
    name: auditd
    state: restarted
    daemon_reload: yes

- name: restart ntpd
  systemd:
    name: ntpd
    state: restarted
    daemon_reload: yes

- name: sysctl reload
  command: sysctl -p
  changed_when: false