# Pod Definition
apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
    version: v1
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
      name: http
    env:
    - name: MESSAGE
      value: "Hello from my-app pod!"

---
# Service Definition
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app  # Targets pods with label app=my-app
  ports:
  - name: http
    port: 80        # Service port
    targetPort: 80  # Container port
    protocol: TCP
  type: ClusterIP   # Internal service

---
# Test Pod for Service Discovery
apiVersion: v1
kind: Pod
metadata:
  name: client-pod
spec:
  containers:
  - name: client
    image: busybox
    command: ['sleep', '3600']  # Keep pod running for testing