name: studentportal build

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'class6/src/**'

  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  IMAGE_REPO_NAME: 879381241087.dkr.ecr.ap-south-1.amazonaws.com/bootcamp-dev-student-portal
  IMAGE_TAG: latest

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: "{{defaultContext}}:class6/src"
            push: true
            tags: ${{ env.IMAGE_REPO_NAME }}:${{ env.IMAGE_TAG }}

    deploy:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}

        - name: Deploy to ECS
          run: |
            # Assuming you have a script or command to deploy to ECS
            echo "Deploying to ECS..."


          # i will update the task definition with the new image URI
          # 
# aws login

# docker build and docker push