name: class13 oidc deploy

on:
  workflow_dispatch:

jobs:
  terraform-dev-apply:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-south-1
      TERRAFORM_VER: 1.8.1
      TERRAFORM_PATH: class13

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VER }}

      - name: Terraform Init
        working-directory: ${{ env.TERRAFORM_PATH }}
        run: terraform init 
      # if only running plan
      # - name: Terraform Plan
      #   working-directory: ${{ env.TERRAFORM_PATH }}
      #   run: terraform plan 
      ### Uncomment the following lines to apply the Terraform configuration ###
      - name: Terraform Apply
        working-directory: ${{ env.TERRAFORM_PATH }}
        run: terraform apply  -auto-approve

      ### Uncomment the following lines to destroy the Terraform configuration ###
      # - name: Terraform Destroy
      #   working-directory: ${{ env.TERRAFORM_PATH }}
      #   run: terraform destroy  -auto-approve